// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuEAXIX5tF7op_mUCkR8kNePwM9MUocsI',
    appId: '1:689505026906:android:54ea9d7a94b08830e0a963',
    messagingSenderId: '689505026906',
    projectId: 'reels-7f647',
    databaseURL: 'https://reels-7f647-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'reels-7f647.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTaHkHAlr5K9D7VsV5lbXeZJBt7aHn9kI',
    appId: '1:689505026906:ios:1dcd6f16ca89cc06e0a963',
    messagingSenderId: '689505026906',
    projectId: 'reels-7f647',
    databaseURL: 'https://reels-7f647-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'reels-7f647.firebasestorage.app',
    iosBundleId: 'com.example.reels',
  );
}
